[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.22.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/samuel/go-zookeeper"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "github.com/karrick/goswarm"
  version = "1.4.7"

[[constraint]]
  name = "github.com/OneOfOne/xxhash"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  branch = "v2"
